### ISSUE TITLE
Prohibit multiple agent starts with the same agent name

### ISSUE THREAD

**Issue by inf17101** [eclipse-ankaios/ankaios#431]
Starting two agents with same name twice one after the other under different users will lead to problems, because each agent tries to use the same agent working directory (`/tmp/ankaios/<agent_name>_io`) causing issues.

Also the `Directory::new` method does unnecessary file system permission expansion when creating a directory. According to #181 only the `/tmp/ankaios` needs full permissions.

## Current Behavior

Starting two agents with same name twice with different users leads to permission problems. In addition, unnecessary permission expansion in the run folder of the agent.

## Expected Behavior

Outputting an error if two agents are started with the same name.

## Steps to Reproduce

Start two agents with the same name under different users including workloads using the control interface.

## Final result

**To be filled by the one closing the issue.**

**Comment by inf17101** [comment]
For #393 to create the config files for workloads on the host file system I could basically re-use the `filesystem.rs::make_dir()` method and also `reopen.rs` does a lot of thinks for file creation and writing to a file. I need both functionalities to create the directory structure and the config file content. The problem is that currently I cannot re-use the existing functions because it is directly coupled into the `control_interface/` component of the agent (and the config files have nothing to do with control interface, so an include would be ridiculous).  In addition, the make_dir function enhances unnecessary the folder permissions if you pass in a path of a directory that shall be created recursively, which is a bug and should be resolved first. Because of this reason, I called the standard library functions to create directories recursively and also writing text and binary to a file directly, because the existing functions are not usable for me. Keep in mind to adapt the utests of `config_files_creator.rs` of the Ankaios agent to get rid of the direct call of the standard library functions and the usage of a tempfile in the utests. After finishing this issue here, the utests might be improved to call the extracted file system functions (maybe there are in common library after finishing this issue)

**Comment by krucod3** [comment]
The current implementation in the cli.rs is really strange with regards to the `run folder` handling. If you want to provide a specific run folder, it must contain a subfolder with the name `<agent name>_io` s.t. the agent can start properly. 
I'll update it to check for the base folder and always create the agent folder.

**Comment by krucod3** [comment]
If two agents are started by different users it could be that the agent folder is not writable by the second (and the following) agent.
There are two possible solutions if we want to handle this without exiting the second agent with an error and both cannot work:
* delete the folder during the exit of the agent (will still not work if the agent crashed, or the machine was cold restarted). Problem: if workloads were still executing we would delete their config files and the Control Interface pipes.
* create each agent folder with a uid suffix enabling the creation of a new folder by the next agent. Problem: if the agent is restarted it will create new pipes for the Control Interface of each workload and the workloads will end up disconnected.

It looks like the only possible solution is indeed to fail the start if a follow-up agent cannot write to it's folder.

**Just a note**: the folders and files in the agent folder are deleted when a workload is deleted. In normal execution no littering of the fs is done.

**Comment by krucod3** [comment]
Done.
